### ISSUE TITLE
skeleton2Graph() function problem

### ISSUE THREAD

**Issue by MrChen18** [mmkamani7/Skeletonization#1]
Hello, thanks for your code. When I run the demo, I got the problem saying "IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices"       skelenton2Graph.py, line 329, in skeleton2Graph edgeLinkedLength = np.array(edgeLength)[map(int, list(np.abs(edgeLinkedNumber) - 1))].tolist().  My work environment is python3.x, windows.  Maybe this is the different version of python that map function return different type result, can you help me solve this problem?

**Comment by mmkamani7** [comment]
Thank you for mentioning the issue. As you stated, this happens because the "map"'s output in Python3 is an iterator, which I transferred it to list and solve the issue.
